language: node_js

node_js:
  - "9"

#before_install:

install:
  npm i

#before_script:

script:
  - npm test

cache:
  directories:
    - "node_modules"

#after_success:

#after_failure:

#after_script:
